### DISCUSSION TITLE
gke support

### DISCUSSION THREAD

**Discussion by deantchi** [topolvm/pvc-autoresizer#277] [Q&A] [answered]
is this app compatible with gke?  
the PVC I'm provision is stuck in `Pending` state

this is the manifest I'm deploying
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-resize
  namespace: pvc-autoresizer
spec:
  containers:
    - name: pod-pvc-resize
      image: google/cloud-sdk:alpine
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: data
          mountPath: /data/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pod-pvc-resize

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pod-pvc-resize
  namespace: pvc-autoresizer
  annotations:
    resize.topolvm.io/storage_limit: 50Gi
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 5Gi
    resize.topolvm.io/inodes-threshold: 20%
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-pvc-autoresizer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: premium-pvc-autoresizer
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    resize.topolvm.io/enabled: "true"
    components.gke.io/component-name: pdcsi
    components.gke.io/layer: addon
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: gcp-compute-persistent-disk-csi-driver
parameters:
  type: pd-ssd
provisioner: topolvm.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

```
