### DISCUSSION TITLE
PVC-autoresizer to support victoriametrics

### DISCUSSION THREAD

**Discussion by decipher27** [topolvm/pvc-autoresizer#318] [Q&A] [answered]
Hi team, would like to know if PVC-autoresizer supports victoriametrics?

**Comment by llamerada-jp** [comment]
Yes. we already use VectoriaMetrics in our environment.

**Comment by decipher27** [comment]
In our setup, each cluster runs its own vmagent to scrape local targets, and then forwards the metrics to a central VictoriaMetrics storage server.

We intentionally avoid deploying a full Prometheus server to reduce resource usage.

Does pvc-autoresizer support querying metrics from vmagent directly? If not, are there any recommended alternatives or workarounds to allow pvc-autoresizer to get the metrics it needs without a Prometheus server?

Any insights or suggestions would be appreciated!

**Reply by llamerada-jp** [reply, marked as answer]
Even if the fullset cluster is not running, is there a mechanism to refer to the collected metrics?
In our environment, we specify VictoriaMetrics's endpoint as follows. Does this help you?

```
# values.yaml
controller:
  args:
    prometheusURL: http://vmselect-vmcluster.monitoring.svc:8481/select/0/prometheus
```
