### ISSUE TITLE
Metrics endpoint seems to not provide all metrics

### ISSUE THREAD

**Issue by oed-guzym** [topolvm/pvc-autoresizer#140]
**Describe the bug**
We want to define alerts based on the metrics, in order to be informed when a limit has been reached or a problem has occurred. But it seems that not all metrics are passed to Prometheus via PodMonitor. Instead of the six existing metrics, we can only access three of them. Even if we access the /metrics endpoint via a port-forward, we only see three metrics.

**Environments**
- v0.4.0 (Chart version)
- Kubernetes (Rancher RKE - v1.21.7)

**To Reproduce**
We installed the chart normally via Helm and added a PodMonitor manually, which looks like this:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pvc-autoresizer
  labels:
    helm.sh/chart: pvc-autoresizer-0.4.0
    app.kubernetes.io/name: pvc-autoresizer
    app.kubernetes.io/instance: xxx
    app.kubernetes.io/managed-by: Helm
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: pvc-autoresizer
  podMetricsEndpoints:
    - port: metrics
```
Then, the following three metrics are automatically available through Prometheus:

![pvc-metrics](https://user-images.githubusercontent.com/90761465/184341997-6a1cf0b0-c634-4775-a28f-d84a1cb27b11.png)

If we use a port-forward to retrieve the metrics via the /metrics endpoint (port: 8080), there are also only three metrics available:
```
# HELP pvcautoresizer_kubernetes_client_fail_total counter that indicates how many API requests to kube-api server are failed.
# TYPE pvcautoresizer_kubernetes_client_fail_total counter
pvcautoresizer_kubernetes_client_fail_total 0
# HELP pvcautoresizer_loop_seconds_total counter that indicates the sum of seconds spent on volume expansion processing loops.
# TYPE pvcautoresizer_loop_seconds_total counter
pvcautoresizer_loop_seconds_total 1471.9785807530034
# HELP pvcautoresizer_metrics_client_fail_total counter that indicates how many API requests to metrics server(e.g. prometheus) are failed.
# TYPE pvcautoresizer_metrics_client_fail_total counter
pvcautoresizer_metrics_client_fail_total 5
```

**Expected behavior**
According to the README, the following metrics should be available through Prometheus and the metrics endpoint:

- pvcautoresizer_kubernetes_cient_fail_total
- pvcautoresizer_metrics_client_fail_total
- pvcautoresizer_loop_seconds_total
- pvcautoresizer_success_resize_total
- pvcautoresizer_failed_resize_total
- pvcautoresizer_limit_reached_total
