### ISSUE TITLE
Error "failed to get volume stats" for online pvc

### ISSUE THREAD

**Issue by nebojsa-ristovic** [topolvm/pvc-autoresizer#199]
Hi, I am getting following error `failed to get volume stats`. 

pvc-autoresizer is started with helm, version is 0.5.0.  
I found that this should be due to PVC being offline, but mine is being used by pod. 

Here is it's storage class manifest:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"false"},"labels":{"component":"aws-ebs-csi-driver"},"name":"premium-rwo"},"parameters":{"iopsPerGB":"10","type":"gp3"},"provisioner":"ebs.csi.aws.com","reclaimPolicy":"Retain","volumeBindingMode":"WaitForFirstConsumer"}
    resize.topolvm.io/enabled: "true"
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    component: aws-ebs-csi-driver
  name: premium-rwo
parameters:
  iopsPerGB: "10"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

And here is pvc manifest:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    resize.topolvm.io/storage_limit: 10Ti
    resize.topolvm.io/threshold: 5%
    resize.topolvm.io/inodes-threshold: 10%
    resize.topolvm.io/increase: 128Gi
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: app-name
  name: pvc-name
  namespace: namespace-name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: premium-rwo
  volumeMode: Filesystem
  volumeName: volume-name
```

Maybe this is not a bug, but my misconfiguration, but I don't see it. 

Thanks in advance!
