### ISSUE TITLE
Build ARM image

### ISSUE THREAD

**Issue by tropnikovvl** [topolvm/pvc-autoresizer#267]
**What should the feature do:**
Hello!
The ARM platform is increasingly gaining popularity and it would be great to be able to build a pvc-autoresizer image for an ARM.

**What is use case behind this feature:**
Launch on ARM instances

By default for convenient multi-architectural builds, `buildx` [are used](https://docs.docker.com/build/building/multi-platform/#multiple-native-nodes). [Link](https://medium.com/@life-is-short-so-enjoy-it/docker-how-to-build-and-push-multi-arch-docker-images-to-docker-hub-64dea4931df9) to a good guide.

But if this method is not convenient for you, then I think you can change the method of build in the release pipeline, for example:
from
```
- run: make image
 ```

to

```
- name: install buildx
  id: buildx
  uses: crazy-max/ghaction-docker-buildx@v1
  with:
    version: latest
- name: build the image
  run: |
    docker buildx build \
    --tag your-username/multiarch-example:latest \
    --platform linux/amd64,linux/arm/v7,linux/arm64 .
```
