### ISSUE TITLE
Enables exposing metrics to Prometheus by Chart

### ISSUE THREAD

**Issue by cmotta2016** [topolvm/pvc-autoresizer#72]
**What should the feature do:**
Enables servicemonitor object creation at Chart.

**What is use case behind this feature:**
Currently, if I need to expose `pvcautoresizer_...` metrics to Prometheus I need to create a service and a scrape config (by servicemonitor object).

**Comment by cmotta2016** [comment]
If it's a good idea, I can open a PR. So, let me know what do you think. :wink:

**Comment by toshipp** [comment]
@cmotta2016 
I consider that servicemonitor is not suitable because pvc-autoresizer can run multiple instances, therefore podmonitor is preferred.
Another concern, we have no experience using PrometheusOperator, we can not maintain this feature.
If you contribute to maintain the feature continuously, we will merge it.
Would you tell me your thought?

**Comment by cmotta2016** [comment]
Well, because our Prometheus stack is configured to use only servicemonitor actually, I configured it, and running multiples replicas (2) I can see metrics from two PODs by querying something like this:
`(increase(pvcautoresizer_success_resize_total[1m])) /6`

> {container="pvc-autoresizer",endpoint="metrics",instance="100.110.78.172:8080",job="pvc-autoresizer",namespace="pvc-autoresizer",pod="pvc-autoresizer-controller-6b799fb7bc-7c8qv",service="pvc-autoresizer"} | 4
> 
> {container="pvc-autoresizer",endpoint="metrics",instance="100.120.139.173:8080",job="pvc-autoresizer",namespace="pvc-autoresizer",pod="pvc-autoresizer-controller-6b799fb7bc-bw278",service="pvc-autoresizer"} | 0

So can you explain the difference between podmonitor and servicemonitor in this context?

**Comment by toshipp** [comment]
I do not use Prometheus Operator, so I expected that only one pod metric is retrieved through a service when using a servicemonitor, but actually, it seems to use an endpoint object.
I think there are no differences except for the need to prepare the service.

**Comment by cmotta2016** [comment]
Yeap, I created the service object to, only to expose the metrics endpoint:
```
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
  labels:
    {{- include "pvc-autoresizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "pvc-autoresizer.name" . }}
{{- end }}
```

And the servicemonitor object:
```
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "pvc-autoresizer.fullname" . }}-controller
  labels:
    {{- include "pvc-autoresizer.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pvc-autoresizer.name" . }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.metrics.scrapeInterval }}s
    scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}s
{{- end }}
```

That works fine.
